### PR TITLE
Add Arabic translation

### LINKED ISSUE #11: Arabic Translation

### PR DESCRIPTION
**Pull request by MicroDroid**
Please note:
 - `Hirschgeist` is not translatable for me. I couldn't find anything about this word on the internet.
 - I do not use this app, and thus, my translations might be slightly off a bit. (though it should still be well enough)

Closes #11

### CODE REVIEW

**Comment by itsmeow** [comment]
Hi. Hirschgeist means "spirit deer" in german. If you could please update the translation to include hirschgeist that would be great. Also "ghost deer". Whichever is best.

**Comment by MicroDroid** [comment]
Yeah, I just thought I'd exclude the `_sa` part since it just applies to most Arab countries anyways. I can also switch to `ar_sa.lang` if you wish, no problem with that.

Also regarding the `Hirschgeist`, can you just give me any sort of an explanation or an article that explains it? I mean, if I translate "spirit deer" as is (روح الغزلان) it'd be very weird and almost nobody will understand what that means unless I miss something.

**Comment by itsmeow** [comment]
https://minecraft.curseforge.com/projects/betteranimalsplus/pages/better-animals-plus/animals-plants-and-mobs/hirschgeist

**Comment by MicroDroid** [comment]
@itsmeow Please take another look, I had just pushed.

**Comment by itsmeow** [comment]
Nice. Thanks.

**Comment by itsmeow** [comment]
Hi! Version 1.2.0 has added new items and mobs, so our translation requires updates. Please submit a new translation.
You will have to translate:
Goat
Goat Cheese
Goat Milk
Wolf Head
Deer Head
Thank you!

**Pull request merged**
