### PR TITLE
Update zh_cn.lang 1.12

### PR DESCRIPTION
**Pull request by Aemande123**
Update zh_cn.lang 1.12.2

Also, does the word "Zotzpyre" mean "Monster Bat"?
I was in Trello see.
In the documents I submitted, "Zotzpyre" was translated in the meaning of "Monster Bat".
If not, please tell me what the word "Zotzpyre" means.

If no problem, I will submit a localized file of 1.14 after a while

<sub>Legal Disclaimer:
ANY PULL REQUEST SUBMITTED TO "The Project" (github.com/itsmeow/betteranimalsplus) AND MERGED INTO A RELEASED VERSION OF THE MODIFICATION (content released via CurseForge.com) BECOMES PROPERTY OF "THE OWNER" (its_meow and partner cybercat5555). ALL RIGHTS TO THE SUBMITTED CONTENT IS TRANSFERRED TO THE OWNER. Credit may or may not be given at The Owner's choice.</sub>

### CODE REVIEW

**Comment by itsmeow** [comment]
Zotzpyre is roughly monster bat, but it has no direct translation, it's a unique name based off a combination of the Aztec god "Zotz" and the suffix of Vampire/Vampyre "pyre"

**Comment by Aemande123** [comment]
> Zotzpyre is roughly monster bat, but it has no direct translation, it's a unique name based off a combination of the Aztec god "Zotz" and the suffix of Vampire/Vampyre "pyre"

Thank you, I will modify it immediately!

**Comment by Aemande123** [comment]
> Zotzpyre is roughly monster bat, but it has no direct translation, it's a unique name based off a combination of the Aztec god "Zotz" and the suffix of Vampire/Vampyre "pyre"

Excuse me, does this "Zotz" mean "Camazotz"?

**Comment by itsmeow** [comment]
Yes, camazotz

**Comment by Aemande123** [comment]
> Yes, camazotz

Ok，Thanks！

**Comment by Aemande123** [comment]
> Yes, camazotz

The modification is complete, and you can pull requests.

**Pull request merged**
